---
apiVersion: v1
kind: Service
metadata:
  name: redmine
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: redmine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
spec:
  selector:
    matchLabels:
      app: redmine
  replicas: 1
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
        - name: redmine
          image: docker.io/duydao2494/cicd-nginx:latest
          imagePullPolicy: "IfNotPresent"
          env:
            - name: REDMINE_DB_MYSQL
              value: mysql
            - name: REDMINE_DB_PASSWORD
              value: "password"
            - name: REDMINE_USERNAME
              value: "user"
            - name: REDMINE_PASSWORD
              value: "password"
            - name: REDMINE_EMAIL
              value: "henrik@loodse.com"
            - name: REDMINE_LANG
              value: "en"
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 120
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            requests:
              memory: "512Mi"
              cpu: "512m"
            limits:
              memory: "512Mi"
              cpu: "512m"
